# Etapa 1: Construir a aplicação
FROM node:22-alpine AS build

# Define o diretório de trabalho
WORKDIR /app

# Copia os arquivos de configuração do package.json e package-lock.json
COPY package*.json ./

# Instala as dependências
RUN npm install

# Copia os arquivos da aplicação para o contêiner
COPY . .

# Etapa 2: Servir a aplicação
FROM node:22-alpine

# Define o diretório de trabalho
WORKDIR /app

# Copia as dependências instaladas e o código-fonte da etapa de construção
COPY --from=build /app .

# Expondo a porta que a aplicação vai usar
EXPOSE 3000

# Comando padrão para iniciar a aplicação
CMD ["node", "server.js"]
