# Etapa 1: Build da aplicação
FROM node:22-alpine AS build

# Define o diretório de trabalho dentro da imagem
WORKDIR /app

# Copia os arquivos de configuração do projeto para a imagem
COPY package.json ./
COPY package-lock.json ./

# Instala as dependências na imagem
RUN npm install

# Copia o restante do código da aplicação para a imagem
COPY . .

# Gera os arquivos estáticos da aplicação na imagem
RUN npm run build

# Etapa 2: Configuração do servidor web
FROM nginx:alpine

# Copia os arquivos estáticos gerados na imagem para o diretório do Nginx
COPY --from=build /app/build /usr/share/nginx/html

# Expondo a porta 80
EXPOSE 80

# Comando para iniciar o Nginx
CMD ["nginx", "-g", "daemon off;"]